[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -std=gnu++17
  -Wall
  -Wextra
  -Werror=return-type
lib_deps =
  madhephaestus/ESP32Servo@^3.0.5

[env:native]
platform = native
build_flags = -std=c++17 -Wall -Wextra
test_build_src = yes
